name: Publish self-contained installation programs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      - run: |
          dotnet publish -c Release --self-contained -r win10-x64
          dotnet publish -c Release --self-contained -r osx-x64
          dotnet publish -c Release --self-contained -r linux-x64
        working-directory: src
      - uses: actions/upload-artifact@v2
        with:
          name: install-quantum
          path: |
            src/bin/Release/net6.0/win10-x64/publish/install-quantum.exe
            src/bin/Release/net6.0/osx-x64/publish/install-quantum
            src/bin/Release/net6.0/linux-x64/publish/install-quantum
